#!/bin/bash
# GitHub Environments Setup Script
# This script will guide you through setting up GitHub environments

echo "🚀 GitHub Environments Setup for Freshfield ERPNext"
echo "=================================================="
echo ""

echo "📋 Step 1: Open your GitHub repository"
echo "Go to: https://github.com/freshfield-life/freshfield-erpnext"
echo ""

echo "📋 Step 2: Navigate to Settings"
echo "1. Click 'Settings' (top right of the repository)"
echo "2. Click 'Environments' (left sidebar)"
echo ""

echo "📋 Step 3: Create Development Environment"
echo "1. Click 'New environment' (green button)"
echo "2. Environment name: dev"
echo "3. Description: Development environment for testing"
echo "4. Click 'Configure environment'"
echo ""
echo "Protection Rules:"
echo "- Required reviewers: Add your GitHub username"
echo "- Wait timer: 0 minutes"
echo "- Deployment branches: Select 'Selected branches' and choose 'main'"
echo ""

echo "📋 Step 4: Add Secrets to Development Environment"
echo "Click 'Add secret' and add these two secrets:"
echo ""
echo "Secret 1: GCP_CREDENTIALS"
echo "1. Go to Google Cloud Console: https://console.cloud.google.com"
echo "2. Click 'IAM & Admin' → 'Service Accounts'"
echo "3. Click 'Create Service Account'"
echo "4. Name: github-actions-deploy"
echo "5. Description: Service account for GitHub Actions deployments"
echo "6. Click 'Create and Continue'"
echo "7. Role: Editor (or Owner for full access)"
echo "8. Click 'Continue' → 'Done'"
echo "9. Click on the service account you just created"
echo "10. Click 'Keys' tab → 'Add Key' → 'Create new key'"
echo "11. Type: JSON"
echo "12. Click 'Create'"
echo "13. Copy the entire JSON content"
echo "14. In GitHub, click 'Add secret'"
echo "15. Name: GCP_CREDENTIALS"
echo "16. Value: Paste the JSON content"
echo "17. Click 'Add secret'"
echo ""

echo "Secret 2: SSH_PRIVATE_KEY"
echo "1. Open Terminal (Mac) or Command Prompt (Windows)"
echo "2. Run: cat ~/.ssh/freshfield_erpnext"
echo "3. Copy the entire content"
echo "4. In GitHub, click 'Add secret'"
echo "5. Name: SSH_PRIVATE_KEY"
echo "6. Value: Paste the SSH key content"
echo "7. Click 'Add secret'"
echo ""

echo "📋 Step 5: Create Staging Environment"
echo "1. Click 'New environment'"
echo "2. Environment name: staging"
echo "3. Description: Staging environment for pre-production testing"
echo "4. Click 'Configure environment'"
echo ""
echo "Protection Rules:"
echo "- Required reviewers: Add your GitHub username + 1 other person"
echo "- Wait timer: 5 minutes"
echo "- Deployment branches: Select 'Selected branches' and choose 'main'"
echo ""
echo "Add the same secrets as Development environment"
echo ""

echo "📋 Step 6: Create Production Environment"
echo "1. Click 'New environment'"
echo "2. Environment name: prod"
echo "3. Description: Production environment for live users"
echo "4. Click 'Configure environment'"
echo ""
echo "Protection Rules:"
echo "- Required reviewers: Add your GitHub username + 2 other people"
echo "- Wait timer: 10 minutes"
echo "- Deployment branches: Select 'Selected branches' and choose 'main'"
echo "- Prevent self-review: Enable"
echo ""
echo "Add the same secrets as other environments"
echo ""

echo "🎉 Step 7: Test the Setup"
echo "1. Go to 'Actions' tab in your repository"
echo "2. Click 'Deploy ERPNext to GCP Environments'"
echo "3. Click 'Run workflow'"
echo "4. Select branch: main"
echo "5. Click 'Run workflow'"
echo "6. Watch it deploy automatically!"
echo ""

echo "✅ You're all set! Your GitHub environments are now configured."
echo "Every time you push code to the main branch, it will automatically:"
echo "1. Deploy to Development"
echo "2. Wait for your approval to go to Staging"
echo "3. Wait for team approval to go to Production"
echo ""

echo "🔗 Repository URL: https://github.com/freshfield-life/freshfield-erpnext"
echo "🔗 Actions URL: https://github.com/freshfield-life/freshfield-erpnext/actions"
echo ""

echo "Need help? Check the error messages in GitHub Actions - they usually tell you exactly what's wrong!"
