name: terraform-apply
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to apply (dev|staging|prod)'
        required: true
        default: 'dev'
permissions:
  contents: read
  id-token: write
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Google Auth (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_TF_SA }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform init
        working-directory: infra/terraform/environments/${{ github.event.inputs.environment }}
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="prefix=env/${{ github.event.inputs.environment }}"

      - name: Terraform apply
        working-directory: infra/terraform/environments/${{ github.event.inputs.environment }}
        run: terraform apply -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -input=false
